---
- name: installing a package
  hosts: all
  become: yes
  tasks:
  - name: installing httpd service
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"    
  - name: start httpd service
    service:
      name: httpd
      state: started
    tags: start httpd service
    when: ansible_os_family == "RedHat"
  - name: install httpd service
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
  - name: start httpd service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
...        
